# Spark Configurations
spark.hadoop.fs.s3a.endpoint=http://minio-server:9000
spark.hadoop.fs.s3a.access.key=Minio Access Key
spark.hadoop.fs.s3a.secret.key=Minio Secret Key
spark.hadoop.fs.s3a.path.style.access=true
spark.hadoop.fs.s3a.impl=org.apache.hadoop.fs.s3a.S3AFileSystem
spark.hadoop.fs.s3a.connection.ssl.enabled=false
spark.hadoop.fs.s3a.aws.credentials.provider=org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider

# Extra Packages to make available for Spark Connect. Need to also be available on the Samba Share
spark.jars.packages org.apache.spark:spark-connect_2.12:3.5.6,org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.9.2,org.apache.spark:spark-hadoop-cloud_2.12:3.5.6,org.postgresql:postgresql:42.7.7,com.amazon.deequ:deequ:2.0.11-spark-3.5

# Points to the Samba Jars Share
spark.driver.extraClassPath /mnt/jars
spark.executor.extraClassPath /mnt/jars

# Iceberg Catalog
spark.sql.catalog.jdbc_cat org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.jdbc_cat.warehouse s3a://iceberg-warehouse
spark.sql.catalog.jdbc_cat.type jdbc
spark.sql.catalog.jdbc_cat.uri jdbc:postgresql://pg-server5432/iceberg_catalog
spark.sql.catalog.jdbc_cat.jdbc.verifyServerCertificate false
spark.sql.catalog.jdbc_cat.jdbc.useSSL false
spark.sql.catalog.jdbc_cat.jdbc.user iceberg_jdbc_user
spark.sql.catalog.jdbc_cat.jdbc.password iceberg_jdbc_password